
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    // Read via process.env (not Prisma's `env()` helper) so config loading
    // never throws when DATABASE_URL is absent - `prisma generate` runs at
    // build time on Vercel with no database env set and needs no URL. The
    // Schema Engine (migrate/db push) still gets the real value: locally via
    // `dotenv/config` above, and in any environment where DATABASE_URL is set.
    url: process.env.DATABASE_URL ?? "",
    // Migrations and introspection need a direct (unpooled) connection. Set
    // DIRECT_URL when DATABASE_URL points at a pooler (e.g. Neon's -pooler
    // host); it falls back to DATABASE_URL for a plain local Postgres.
    directUrl: process.env.DIRECT_URL || process.env.DATABASE_URL || "",
  },
});
